pipeline {
    agent {
        docker {
            image 'ubuntu:21.04'
            args '-v $HOME/workspace/helios-webrtc:/helios-webrtc -w /helios-webrtc'
            reuseNode true 
        }
    }
    stages {
        stage('Import Dependencies') {
            steps {
                sh 'ls'
                sh 'apt update'
                sh 'apt install -y git curl wget'
                sh 'git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git'
                sh 'export PATH=$PATH:$PWD/depot_tools'
                sh 'fetch --nohooks webrtc_android'
                sh 'gsync sync'
                sh 'cd src'
                sh './build/install-build-deps.sh'
                sh 'gclient revert'
                sh 'gclient sync'
            }
        }
        stage('Build') {
            steps {
                sh 'cd src'
                sh 'tools_webrtc/android/build_aar.py'
            }
        }
    }
}