pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'ubuntu'
                    reuseNode true // this enables to use the current workspace inside docker
                }
            }
            steps {
                sh 'ls -lha'
            }
        }
    }
}